[package]
name = "collatz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
pollster = "0.2"
wgpu = { version = "0.15", features=["spirv"]}

