[package]
name = "image-blur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pollster = "0.2"
wgpu = { version = "0.15", features=["spirv"]}

